"""Gmail delivery client — reads credentials from delivery_config.json or env vars."""

import json
import os
import smtplib
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path


def _load_config() -> dict:
    config_path = Path(__file__).resolve().parents[3] / "delivery_config.json"
    if config_path.exists():
        return json.loads(config_path.read_text(encoding="utf-8"))
    return {}


def get_gmail_credentials() -> tuple[str, str]:
    """Return (gmail_user, app_password) from config file or environment."""
    config = _load_config()
    user = os.getenv("GMAIL_USER") or config.get("GMAIL_USER", "")
    password = os.getenv("GMAIL_APP_PASSWORD") or config.get("GMAIL_APP_PASSWORD", "")
    return user, password


def send_diligence_email(
    to_email: str,
    company: str,
    report_html: str,
    drive_link: str = "",
) -> None:
    """Send the diligence report via Gmail SMTP.

    Attaches the HTML report and includes an optional Google Drive link.
    Raises RuntimeError if credentials are missing.
    """
    gmail_user, app_password = get_gmail_credentials()
    if not gmail_user or not app_password:
        raise RuntimeError(
            "Gmail credentials not found. Add GMAIL_USER and GMAIL_APP_PASSWORD "
            "to delivery_config.json or set them as environment variables."
        )

    msg = MIMEMultipart("mixed")
    msg["Subject"] = f"Investment Diligence Report Ready — {company}"
    msg["From"] = gmail_user
    msg["To"] = to_email

    drive_section = (
        f'<p><a href="{drive_link}" style="background:#0f3460;color:white;'
        f'padding:0.6rem 1.2rem;border-radius:4px;text-decoration:none;'
        f'font-weight:600;">View on Google Drive</a></p>'
        if drive_link else ""
    )

    body_html = f"""
    <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;
                max-width:600px;margin:0 auto;color:#1a1a2e;">
      <div style="background:linear-gradient(135deg,#1a1a2e,#0f3460);
                  color:white;padding:2rem;border-radius:8px 8px 0 0;">
        <h1 style="margin:0;font-size:1.2rem;">AI Investment Diligence Copilot</h1>
      </div>
      <div style="background:#f8f9fc;padding:2rem;border-radius:0 0 8px 8px;
                  border:1px solid #e0e0e0;">
        <h2 style="margin:0 0 1rem;">Diligence Report Ready</h2>
        <p>Your AI-generated investment diligence report for
           <strong>{company}</strong> has been completed.</p>
        <p>The full report is attached to this email as an HTML file.</p>
        {drive_section}
        <hr style="border:none;border-top:1px solid #e0e0e0;margin:1.5rem 0;" />
        <p style="font-size:0.8rem;color:#888;">
          Generated by Policy-Aware AI Investment Diligence Copilot.
          For internal use only.
        </p>
      </div>
    </div>
    """
    msg.attach(MIMEText(body_html, "html"))

    attachment = MIMEBase("text", "html")
    attachment.set_payload(report_html.encode("utf-8"))
    encoders.encode_base64(attachment)
    safe_name = company.replace(" ", "_")
    attachment.add_header(
        "Content-Disposition",
        f'attachment; filename="{safe_name}_diligence_report.html"',
    )
    msg.attach(attachment)

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(gmail_user, app_password)
        server.send_message(msg)
